#!/bin/bash

echo "removing expirement"
rm -r ./expirement/fresh
rm -r ./expirement/stale
rm -r ./tmp/jobs #we replace this dir
rm ./tmp/logs/*

echo "creating expirement"
unzip -o expirement.zip > /dev/null 2>&1

echo "moving files"
mv  ./expirement/exampleCurr ./expirement/fresh
mv  ./expirement/exampleOld  ./expirement/stale
rm -r   ./expirement/exampleJobs 

rm ./expirement/fresh/.zip

echo "creating scan files"
./scanAndGenJobsFS.sh
