#!/bin/bash

rm -r ./expirement/fresh
rm -r ./expirement/stale
rm -r ./tmp/jobs #we replace this dir
rm ./tmp/logs/*

unzip -o expirement.zip

mv  ./expirement/exampleCurr ./expirement/fresh
mv  ./expirement/exampleOld  ./expirement/stale
mv  ./expirement/exampleJobs ./tmp/jobs

rm ./expirement/fresh/.zip