#!/bin/bash
./resetExpirement > /dev/null
/usr/bin/time shiftc --wait --host-list=dlsv225 --sync-fast -R -P -d --clients=38 ./expirement/fresh/* ./expirement/stale/

read -p "Press Enter to see diff."

diff -qr ./expirement/fresh ./expirement/stale 

read -p "Press Enter to run distsync."

./resetExpirement > /dev/null
/usr/bin/time java -jar distsync.jar -f ./expirement/fresh -s ./expirement/stale -m dlsv225

read -p "Press Enter to see diff."

diff -qr ./expirement/fresh ./expirement/stale 
